### ISSUE TITLE
store.useState is not a function

### ISSUE THREAD

**Issue by midnightcoder-pro** [aszczepanek/react-gstate#8]
Probably an error in the documentation or a version discrepancy, but useGlobalState works

**Comment by aszczepanek** [comment]
Yes. error in documentation after rename after 2.0.0 release, which required to change useState to useGlobalState in order to fix react dev tools (useState is somehow special name for tools, and they didn't work properly with that name).
Fixed in 2d7f5536eb2e7387ec7adfa3f534508a3075acea
